### PR TITLE
Branch archive bugfix

### LINKED ISSUE #161: GUI resets to full list of people after reminder execution

### LINKED ISSUE #164: Incorrect index for unarchive command
Currently, if I do: 
1.  archive 1 (archives Alex Yeoh)
2. activelist (does not display Alex Yeoh)
3. unarchive 1 will still successfully unarchive Alex Yeoh

Based on our user guide, the index that the user types in should be based on the index in the displayed clients list. Since Alex Yeoh was not the first client displayed from `activelist`, `unarchive 1` should not have worked

### LINKED ISSUE #169: Automatic unarchiving of client
Currently, when I star / edit / add reminder / note to an archived client, the command successfully executes and automatically unarchives the client. Not sure if this was the intended purpose of archive?

### LINKED ISSUE #172: Displaying full list after command execution
After any command executes, FinHub automatically displays back `list` instead of `activelist`. I think this should not be the case because archived clients should be "hidden" unless user wants to view `archivelist`.

### LINKED ISSUE #179: Confusion with the three different list
Issue:
Currently, when you have archived person and unarchived person, when you run the application, the activelist will be shown. However, after utilizing the application (running some basic command like add person, add reminders, star, etc, the entire list is displayed instead of the active list) 

Steps to reproduce:
1. Ensure you have archived and unarchived person
2. close and re-run the application
3. run a random command like "star 1"
4. you will see the entire list of clients.

Potential improvement:
Can provide better segmentation which is just normal list of active person and list of archived person

### LINKED ISSUE #180: Acceptance of wrong unarchive command.
Currently, if you go to archivelist with at least 1 client inside and do "archive 1", output message is "This person is already archived."

Image

However, when you go to activelist with clients and do "unarchive 1", output message of  "This person is already unarchived." should be shown but not shown. instead a command is executed.

### LINKED ISSUE #181: Archived client still can be search using find
Issue: 
Despite archiving someone, i will still see that client when i use find on the client's name.

Steps to reproduce bug:
1. archive a client
2. display the active clients by using activelist
3. use find with the name of the archived client as argument
4. you will see the archived client display in the list

Image

### LINKED ISSUE #183: Archive list shows general reminder despite no archived client
issue:
General reminder is displayed despite being in archive list and having no archived client. This may be confusing for the user.

Steps to reproduce:
1. unarchive all clients.
2. add a reminder to a active client
3. display the archive list by using archivelist
4. you will see that general reminder is still displayed.

Image

### PR DESCRIPTION
**Pull request by JunhaoW3**
Close #181 Close #180 Close #179 Close #172 Close #169 Close #164 Close #161 Close #183

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -114,8 +114,10 @@ private static Person createEditedPerson(Person personToEdit, EditPersonDescript
         ArrayList<MeetingNote> updatedMeetingNotes = personToEdit.getMeetingNotes();
         // edit command does not allow editing of starred
         boolean isStarred = personToEdit.isStarred();
+        // edit command does not allow editing of archive
```
Comment (farbutnear) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: good call, client shouldnt be archived or unarchived through edit but rather through archive and unarchive commmands
